# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
#  check-dist:
#    runs-on: ubuntu-latest
#    steps:
#      - name: test actions
#        uses: user-zouyu/ssh-actions@main
#        with:
#          host: ${{ secrets.HOST }}
#          port: ${{ secrets.PORT }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          script: |
#            ls -al
#            pwd
#            docker ps
  echo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "ls"
        run: "ls -al"